# Generated by Django 4.0.3 on 2022-04-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_solution_mod_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
