# Generated by Django 4.0.3 on 2022-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_solution_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='vulnerable_code',
            field=models.TextField(default=' '),
        ),
    ]
