# Generated by Django 4.0.3 on 2022-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_solution_vulnerable_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='fixed_code',
            field=models.TextField(default=' '),
        ),
    ]
