# Generated by Django 4.0.3 on 2022-03-03 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_patient_patient_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_since',
            field=models.CharField(default=datetime.date.today, max_length=30),
        ),
    ]
