# Generated by Django 4.0.3 on 2022-03-03 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_patient_patient_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_since',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
